### ISSUE TITLE
大佬你安装有啥特殊操作没，我安装系统卡着itlwm:taskq task_add iwx_newstate_task add to queue不动

### ISSUE THREAD

**Issue by yuduobing** [codeMauguin/RedmiBook14II-i5-1035G1-EFI#2]

**Comment by codeMauguin** [comment]
是redmibook14II英特尔版本么i5 1035G1，关闭bios安全模式，其他的我没有动，还有cfg这个你如果没解锁，将AppleXcpmCfgLock这个修改下，我等会把我现在这个的EFI上传下，你这个报错是无线网的问问题，将config.plist中的itlwm都取消勾选，试试

**Comment by codeMauguin** [comment]
将驱动中AirportItlwm.kext取消开启试试，最新的文件中不包含itlwm这个驱动了
